### PR TITLE
Fix parsing special characters error in tour-duplicate

### LINKED ISSUE #198: Fix parsing special characters error in tour-duplicate

### PR DESCRIPTION
**Pull request by nrysho**
Fixes #198

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/TourDuplicateCommandParser.java [hunk 1]
```diff
@@ -35,9 +36,11 @@ public TourDuplicateCommand parse(String args) throws ParseException {
 
         argMultimap.verifyNoDuplicatePrefixesFor(PREFIX_NAME);
 
-        String name = argMultimap.getValue(PREFIX_NAME).get();
+        String nameValue = argMultimap.getValue(PREFIX_NAME).get();
+        Tour tour = ParserUtil.parseTour(nameValue);
+        String validatedName = tour.getTourName();
 
-        return new TourDuplicateCommand(index, name);
+        return new TourDuplicateCommand(index, validatedName);
```
Comment (Ash-L7) [inline src/main/java/seedu/address/logic/parser/TourDuplicateCommandParser.java:43]: lgtm

File: src/test/java/seedu/address/logic/parser/TourDuplicateCommandParserTest.java [hunk 2]
```diff
@@ -69,6 +70,11 @@ public void parse_nonIntegerIndex_failure() {
                 String.format(MESSAGE_INVALID_COMMAND_FORMAT, TourDuplicateCommand.MESSAGE_USAGE));
     }
 
+    @Test
+    public void parse_invalidName_returnsFailure() {
+        assertParseFailure(parser, "1 n/Invalid@Tour#Name", Tour.MESSAGE_CONSTRAINTS);
+    }
+
```
Comment (Ash-L7) [inline src/test/java/seedu/address/logic/parser/TourDuplicateCommandParserTest.java:77]: lgtm

**Review by gluee003 — APPROVED** [review]
lgtm
