### PR TITLE
Fix/PE Dry Run Bugs

### LINKED ISSUE #180: UI: Tour window gets cropped out when window is scaled down
Part of the UI will be cropped/can't be seen when the window is resized to below a certain size

Image

### LINKED ISSUE #202: [PE-D][Tester B] Duplicate contacts allowed when names differ but all other details are identical
**Description**  
The application allows multiple contacts with identical details (phone, email, and address) as long as the name is different. This results in duplicate entries representing the same real-world entity.

**Steps to Reproduce**  
1. Run:  
   `add type/person n/John Doe p/98765432 e/john@example.com a/311 Clementi Ave 2`  
2. Run:  
   `add type/person n/Jonathan Doe p/98765432 e/john@example.com a/311 Clementi Ave 2`  
3. View the contact list  

**Expected Behavior**  
The application should prevent adding duplicate contacts when key identifying fields (e.g., phone or email) are identical, even if the name differs.

**Actual Behavior**  
Both contacts are added successfully despite having identical details.

**Screenshots**  

Image
Image
Image

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #208: [PE-D][Tester B] Editing contact allows duplicate entries with different names but identical details
**Description**  
The application allows editing a contact such that it becomes identical to another existing contact in all fields except the name. This results in duplicate entries representing the same entity.

**Steps to Reproduce**  
1. Run:  
   `add type/person n/John Doe p/91234567 e/john@example.com a/test`  
2. Run:  
   `add type/person n/Jane Smith p/98765432 e/jane@example.com a/test`  
3. Run:  
   `edit 2 p/91234567 e/john@example.com a/test`  

**Expected Behavior**  
The application should prevent creation of duplicate contacts with identical details, even if the name differs, or clearly define uniqueness constraints.

**Actual Behavior**  
The edit is allowed, resulting in two contacts with identical phone, email, and address but different names.

**Screenshots**  

Image

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #210: [PE-D][Tester B] Editing a contact with unchanged values still reports a successful edit
**Description**  
When editing a contact using the same values as the existing fields, the application still reports that the contact has been edited, even though no actual changes were made.

**Steps to Reproduce**  
1. Run:  
   `add type/person n/John Doe p/98765432 e/john@example.com a/Address`  
2. Run:  
   `edit 1 n/John Doe`  

**Expected Behavior**  
The application should detect that no changes were made and either notify the user or avoid performing the edit.

**Actual Behavior**  
The application reports a successful edit despite no changes.

**Screenshots**

Image

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #227: [PE-D][Tester E] edit command resets filtered view but delete does not — inconsistent behavior
## Description

The `edit` command resets the filtered contact list back to showing all contacts, while the `delete` command preserves the current filter. This inconsistency is confusing — both commands operate on a contact in the filtered view, but only `edit` breaks the user out of the filtered context.

## Steps to reproduce

**Test 1 — edit resets filter:**
1. `favourite-add 1` — mark first contact as favourite
2. `favourite-add 2` — mark second contact as favourite
3. `favourite-view` — filter to show only favourite contacts
4. `edit 1 p/99999999` — edit the first contact in the filtered list
5. Observe: the filter is reset and **all contacts** are now shown

**Test 2 — delete preserves filter:**
1. `favourite-view` — filter to show only favourite contacts again
2. `delete 1` — delete the first contact in the filtered list
3. Observe: the filter is **preserved** and only remaining favourites are shown

## Expected behavior

Both `edit` and `delete` should behave consistently — either both preserve the filter or both reset it. Ideally, both should preserve the filter so the user can continue working in the filtered context.

## Actual behavior

- `edit` resets the filter to show all contacts
- `delete` preserves the current filter

## Why this is problematic

- A user working within `favourite-view` or `tour-view` expects to stay in that filtered context while making changes. After editing a contact, the entire list suddenly reappears, breaking their workflow and forcing them to re-apply the filter.
- The inconsistency between `edit` and `delete` makes the app's behavior unpredictable — the user cannot know in advance whether a command will preserve their current view or not.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #238: [PE-D][Tester C] tour-assign: success message
When successfully assigning a tour, the success message does not include the newly assigned tour of the contact. Should the success message reflect the new change?

Image

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### PR DESCRIPTION
**Pull request by Reiner-Ong**
* Fixes #238, Success message for tour-assign and assign now correctly reflects the tour. 
* Fixes #210, Add validation checks for edit commands that do no changes.
* Fixes #227, Removed filter reset for edit command.
* Fixes #180, Placed minimum UI size 
* Fixes #202, #208, Give warning for similar fields

### CODE REVIEW

**Review by gluee003 — APPROVED** [review]
lgtm 👍

File: src/main/java/seedu/address/logic/Messages.java [hunk 1]
```diff
@@ -86,4 +89,47 @@ public static String format(Tour tour) {
         return tour.getTourName();
     }
 
+    /**
+     * Returns a warning message listing contacts that share the same phone, email, or address
+     * as {@code target}, excluding {@code excluded} (for edits, pass the original contact; for
+     * adds, pass null). Returns an empty string if no overlaps are found.
+     */
+    public static String getFieldOverlapWarning(Model model, Contact target, Contact excluded) {
```
Comment (nrysho) [inline src/main/java/seedu/address/logic/Messages.java:97]: lgtm

File: src/main/java/seedu/address/logic/commands/contact/AddCommand.java [hunk 2]
```diff
@@ -80,7 +80,8 @@ public CommandResult execute(Model model) throws CommandException {
 
         assert model.hasContact(contactToAdd) : "Contact should have been added";
         logger.fine(String.format("Added contact: %s", contactToAdd));
-        return new CommandResult(String.format(MESSAGE_SUCCESS, Messages.format(contactToAdd)));
+        String warning = Messages.getFieldOverlapWarning(model, contactToAdd, null);
```
Comment (nrysho) [inline src/main/java/seedu/address/logic/commands/contact/AddCommand.java:83]: lgtm

File: src/main/java/seedu/address/logic/commands/contact/EditCommand.java [hunk 3]
```diff
@@ -101,11 +101,11 @@ public CommandResult execute(Model model) throws CommandException {
 
         model.setContact(contactToEdit, editedContact);
         model.commitAddressBook();
-        assert contactToEdit != editedContact : "Original contact must have been edited";
         logger.fine(String.format("Edited contact from %s to %s", contactToEdit, editedContact));
 
-        model.updateFilteredContactList(PREDICATE_SHOW_ALL_CONTACTS);
-        return new CommandResult(String.format(MESSAGE_EDIT_CONTACT_SUCCESS, Messages.format(editedContact)));
+        String warning = Messages.getFieldOverlapWarning(model, editedContact, contactToEdit);
```
Comment (nrysho) [inline src/main/java/seedu/address/logic/commands/contact/EditCommand.java:106]: lgtm

**Review by nrysho — APPROVED** [review]
