### PR TITLE
Fix index overflow error

### LINKED ISSUE #257: [PE-D][Tester A] Unexpected Delete Behaviour Throws Error for Positive Integers
UG states the error details for indexes that are larger than list size should be consistent as `The contact index provided is invalid` but shows `Invalid command format!` error for a large positive integer that overflows.

Fix error handling for overflowing integers.

Image

Image

Image

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by nrysho**
Fixes #257

### CODE REVIEW

**Review by gluee003 — APPROVED** [review]
lgtm :+1:. rmb to fix checkstyle

File: src/main/java/seedu/address/commons/util/StringUtil.java [hunk 1]
```diff
@@ -67,6 +67,22 @@ public static boolean isNonZeroUnsignedInteger(String s) {
...
+    public static boolean isPositiveOverflowNumber(String s) {
+        if (!s.matches("\\d+")) {
+            return false;
+        }
+        try {
+            Integer.parseInt(s);
+            return false;
+        } catch (NumberFormatException e) {
+            return true;
+        }
```
Comment (gluee003) [inline src/main/java/seedu/address/commons/util/StringUtil.java:85]: missing closing brace for method

**Review by gluee003 — CHANGES_REQUESTED** [review]
