### PR TITLE
Normalise whitespaces for contact/tour names during parsing

### LINKED ISSUE #215: [PE-D][Tester B] Contacts with visually identical names treated as different due to whitespace differences
**Description**  
The application treats names with different internal whitespace as distinct, allowing multiple contacts that appear visually identical to be stored as separate entries.

**Steps to Reproduce**  
1. Run:  
   `add type/person n/kie john p/91234567 e/a1@example.com a/test`  
2. Run:  
   `add type/person n/kie     john p/98765432 e/a2@example.com a/test`  

**Expected Behavior**  
Names that differ only by whitespace should be normalised (e.g., multiple spaces reduced to a single space) and treated as the same, or flagged as potential duplicates.

**Actual Behavior**  
Both contacts are accepted as separate entries despite having visually identical names.

**Screenshots**  

Image

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by gluee003**
Fixes #215

### CODE REVIEW

File: src/main/java/seedu/address/commons/util/StringUtil.java [hunk 1]
```diff
@@ -65,4 +65,16 @@ public static boolean isNonZeroUnsignedInteger(String s) {
...
         }
     }
+
+    /**
+     * Returns a name with whitespaces normalised.
+     * If there are multiple whitespaces between words, it will be normalised to a single whitespace.
+     * e.g normaliseTrimmedName("Le  Bron     James") == "Le Bron James"
+     * @param name A string that has been trimmed
+     */
+    public static String normaliseTrimmedName(String name) {
```
Comment (nrysho) [inline src/main/java/seedu/address/commons/util/StringUtil.java:75]: lgtm

**Review by nrysho — APPROVED** [review]

**Review by wincura — COMMENTED** [review]
LGTM

File: src/main/java/seedu/address/commons/util/StringUtil.java (hunk 1 above)
Comment (wincura) [inline src/main/java/seedu/address/commons/util/StringUtil.java:75]: Good choice to have the function in `StringUtil.java`.

**Review by wincura — COMMENTED** [review]
Good to go.
